# Generated by Django 4.1.1 on 2022-12-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_feeding"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clothes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name="feeding",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterField(
            model_name="feeding",
            name="date",
            field=models.DateField(verbose_name="feeding date"),
        ),
        migrations.AddField(
            model_name="animal",
            name="clothes",
            field=models.ManyToManyField(to="main_app.clothes"),
        ),
    ]
